# This file was generated by GoReleaser. DO NOT EDIT.
cask "treecat" do
  name "treecat"
  desc "Recursive directory tree + syntax-highlighted file contents"
  homepage "https://github.com/carterlasalle/treecat"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "treecat"

  on_macos do
    on_intel do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_darwin_amd64.tar.gz"
      sha256 "019f510ed69504e3082895795c6dea72de6a2314cc33643c2fce2b3de3bfbadd"
    end
    on_arm do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_darwin_arm64.tar.gz"
      sha256 "37b37e3cd0454e0e9e0e79714439e2a7bbb949f3ebc4c906cf4dc8192956383a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_linux_amd64.tar.gz"
      sha256 "14cccc56bcd8b12025c53a4f9a74ebdb08d674ac8c9f752108973dddf8878934"
    end
    on_arm do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_linux_arm64.tar.gz"
      sha256 "4cc1f9fbb2789ffe86a62ce3c342e61626c4ab3b3d24c711dd8df0b73dfff9e5"
    end
  end

  # No zap stanza required
end
