# This file was generated by GoReleaser. DO NOT EDIT.
cask "treecat" do
  name "treecat"
  desc "Recursive directory tree + syntax-highlighted file contents"
  homepage "https://github.com/carterlasalle/treecat"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "treecat"

  on_macos do
    on_intel do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_darwin_amd64.tar.gz"
      sha256 "d842e0cc6d5a4dbb1cdbe82cd41b0a0b18727c97a34306d30782a45970ed2664"
    end
    on_arm do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_darwin_arm64.tar.gz"
      sha256 "9beaca4e07be50f944449f9cfca12badd8619e62cb28d043a4e1306374acd827"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_linux_amd64.tar.gz"
      sha256 "709ba152f2c80cd8e23476883a08def22e29c30c0a2521dbfe8ce5b87986f49d"
    end
    on_arm do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_linux_arm64.tar.gz"
      sha256 "ef9dceea6cd2325c9c48a6779f463b98d7acaaf77278d3648ad534715633b230"
    end
  end

  # No zap stanza required
end
