# This file was generated by GoReleaser. DO NOT EDIT.
cask "treecat" do
  name "treecat"
  desc "Recursive directory tree + syntax-highlighted file contents"
  homepage "https://github.com/carterlasalle/treecat"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "treecat"

  on_macos do
    on_intel do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_darwin_amd64.tar.gz"
      sha256 "181c51d39d77a64c4095319ce5f1db7313f5814702c38c83ae8498ccf29501f2"
    end
    on_arm do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_darwin_arm64.tar.gz"
      sha256 "158df0ab53d6d22bb2438234e85ba76d941e5da7e5e002d3c9a6763ecd46269a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_linux_amd64.tar.gz"
      sha256 "93433692cdc067aec6ee21083271393946c46865814ab4b3f7274e613cce0fbb"
    end
    on_arm do
      url "https://github.com/carterlasalle/treecat/releases/download/v#{version}/treecat_linux_arm64.tar.gz"
      sha256 "0f9e0b6c714703e2a5ea007a34d62ee8e04ee6dd3e187c4b0273291d1e1bb9ff"
    end
  end

  # No zap stanza required
end
