# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Treecat < Formula
  desc "Recursive directory tree + syntax-highlighted file contents"
  homepage "https://github.com/carterlasalle/treecat"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carterlasalle/treecat/releases/download/v0.1.4/treecat_darwin_amd64.tar.gz"
      sha256 "d8c6f38d73876ad6f15128c58dd7495269d6f729033a0ad2c0a4f968af72bcc2"

      define_method(:install) do
        bin.install "treecat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carterlasalle/treecat/releases/download/v0.1.4/treecat_darwin_arm64.tar.gz"
      sha256 "00de6b60e028b7723837e239a12deaf3fcb81011744839f73bfc54977111993c"

      define_method(:install) do
        bin.install "treecat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carterlasalle/treecat/releases/download/v0.1.4/treecat_linux_amd64.tar.gz"
      sha256 "98c7eb35ccb850fda513a09c0a642717fc5c90462c09847356f38b0e8a6b6c76"
      define_method(:install) do
        bin.install "treecat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carterlasalle/treecat/releases/download/v0.1.4/treecat_linux_arm64.tar.gz"
      sha256 "e0f376738a91526ba9f6e612822ba6b96f2279e024e4c278294923c330d611d3"
      define_method(:install) do
        bin.install "treecat"
      end
    end
  end
end
